openapi: "3.0.0"
info:
  description: "Skeleton Service for creating models and API interface for rest ws to give to clients"
  version: "0.0.1"
  title: "Model Service Skeleton API"
  contact:
    email: "tinashehondo@gmail.com"
tags:
  - name: "user"
    description: "User - dummy tag to initialise service"
#servers:
#  - url: http://localhost:8000/
#    description: "local host"

paths:
  /notification/sms/{refId}:
    get:
      description: Get a single message by reference id.
      # operationId is an optional unique string used to identify an operation. If provided, these IDs must be unique among all operations described in my API.
      operationId: getMessageByReferenceId
      parameters:
        - in: path
          name: refId
          schema:
            type: string
          required: true
          description: reference ID of the message to get

      responses:
        200:
          description: The Message Response object with sms details fetched by a ref ID
          content:
            application/json:
              schema:
                $ref: ./message-response.yml#/MessageResponse
        400:
          description: HTTP 400 Failed to send SMS
          content:
            application/json:
              schema:
                $ref: ./errors/problem.yml#/Problem
        401:
          description: Unauthorized - The request requires user authentication
        403:
          description: Forbidden - The server understood the request, but is refusing it or
            the access is not allowed.
        404:
          description: Resource not found
        500:
          description: HTTP 500 Error Response
          content:
            application/json:
              schema:
                $ref: ./errors/problem.yml#/Problem

  /notification/sms:
    post:
      description: sending sms notifications
      operationId: sendSMSNotification
      tags:
        - notificationService
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./message.yml#/Message
        description:  Allows sending on sms notification
        required: true
      responses:
        200:
          description: The Message Response object with sms details and a ref ID
          content:
            application/json:
              schema:
                $ref: ./message-response.yml#/MessageResponse
        400:
          description: HTTP 400 Failed to send SMS
          content:
            application/json:
              schema:
                $ref: ./errors/problem.yml#/Problem
        401:
          description: Unauthorized - The request requires user authentication
        403:
          description: Forbidden - The server understood the request, but is refusing it or
            the access is not allowed.
        404:
          description: Resource not found
        500:
          description: HTTP 500 Error Response
          content:
            application/json:
              schema:
                $ref: ./errors/problem.yml#/Problem

